language: English
agents:
- name: Agent_1
  personality: You are a college student
  model: deepseek/deepseek-v3.2-exp
  temperature: 0.47217217295409364
  memory_character_limit: 25000
  reasoning_enabled: true
- name: Agent_2
  personality: You are a college student
  model: deepseek/deepseek-v3.2-exp
  temperature: 0.47217217295409364
  memory_character_limit: 25000
  reasoning_enabled: true
- name: Agent_3
  personality: You are a college student
  model: z-ai/glm-4.5-air
  temperature: 0.47217217295409364
  memory_character_limit: 25000
  reasoning_enabled: true
utility_agent_model: gemini-2.0-flash-lite
utility_agent_temperature: 0.0
phase2_rounds: 10
distribution_range_phase2:
- 2
- 6
income_class_probabilities:
  high: 0.05
  medium_high: 0.1
  medium: 0.5
  medium_low: 0.25
  low: 0.1
original_values_mode:
  enabled: true
transcript_logging:
  enabled: true
logging:
  verbosity_level: debug
